// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using autoria_api.data;

#nullable disable

namespace autoria_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240706101921_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("autoria_api.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Car_number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Car_vin_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Carrying_capacity_ton")
                        .HasColumnType("REAL");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Engine_capacity")
                        .HasColumnType("REAL");

                    b.Property<int>("Engine_type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagesPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Mileage")
                        .HasColumnType("REAL");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number_of_seats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Occasion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Owners_number")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PriceUSD")
                        .HasColumnType("REAL");

                    b.Property<string>("Road_accident")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Transmission_type")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Wanted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
