services:
  api:
    build:
      context: ./back/autoria-api
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=/app/DBautoria.db
    volumes:
      - ./back/autoria-api/autoria-api/DBautoria.db:/app/DBautoria.db
      - ./back/autoria-api/autoria-api/Images:/app/Images

  frontend:
    build:
      context: ./front/autoria
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - api