---
- name: Diplom project docker deploy
  hosts: diplom
  gather_facts: true
  become: true
  become_method: sudo
  vars_files: diplom_vars.yml
  tasks:
    - import_tasks: install_docker.yml
    - import_tasks: Install_Prometheus.yml
#   - import_tasks: run_docker_compose.yml
#    - import_tasks: run_docker.yml