---
- name: Run `docker-compose up` again
  community.docker.docker_compose:
    project_src: /root/autoria
    build: false
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output